name: Build and Deploy to Minikube

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure Docker for Minikube
      run: |
        & minikube -p minikube docker-env --shell powershell | Invoke-Expression

    - name: Build Docker image in Minikube
      run: docker build -t frontend:latest .

    - name: Deploy to Minikube
      run: |
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml
#newcommit